#!/bin/bash
# Version 1.0
# Copyright (c) 2023 3nine
# Author: 3nine
# License: MIT
# https://github.com/3nine/pi/main/LICENSE.md

# Setze die Farben für die Ausgabe
GREEN='\e[32m'
BLUE='\e[34m'
CYAN='\e[36m'
YELLOW='\e[33m'
RED='\e[31m'
GRAY='\e[90m'
RESET='\e[0m'

show_help() {
  GREEN='\e[32m'
  BLUE='\e[34m'
  CYAN='\e[36m'
  YELLOW='\e[33m'
  RED='\e[31m'
  GRAY='\e[90m'
  RESET='\e[0m'

  echo -e "${GRAY}Verwendung:${RESET}"
  echo -e "${GRAY}  ./pi-netbox-install              - Führt das Skript aus.${RESET}"
  echo -e "${GRAY}  ./pi-netbox-install help or ?    - Zeigt diese Hilfe an.${RESET}"
  exit 0
}

pause() {
  sleep 2 # 2 Sekunden Pause
}

check_dialog_installed() {
  echo -e "[ ${YELLOW}INFO ]"
}

check_netbox_installed() {
  
}

# --------> Start <--------

# Prüfe ob Arg1 "?" oder "help" ist
if [ "$1" = "?" ] || [ "$1" = "help" ]; then
  show_help
fi
